spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://localhost:8180/realms/pf/protocol/openid-connect/certs

  cors:
    allowed-origins: "*"
    allowed-methods: "*"
    allowed-headers: "*"

